  const move = [
    "Prise de main alignée pour se décaler en épaule",
    "Lancer de pied pour reprendre l'équilibre",
    "Lâché talon pour aller chercher une main loin (allongé)",
    "Croisé ou décroisé",
    "Opposition de main",
    "Prise bonne uniquement en passant de l'autre côté",
    "Passer de deux mains groupées à mains écartées (drapeau de pied)",
    "Chercher une épaule loin derrière puis ramener",
    "Mouvement d'épaule de profil avec deux prises en opposition (fissure)",
    "Mains face à face mais éloignées, blocage épaule et triceps",
    "Mini scorpion avec pied",
    "Explosivité vers une prise plus haute en ouvrant les bras",
    "Inversée avec pied haut",
    "Canne à pêche de pied",
    "Canne à pêche de main",
    "Mouvement électrique de main basse vers main haute en gardant le même pied",
    "Mains groupées avec pied diagonal vers main haute (impulsion)",
    "Pif Paf: ramener puis exploser dans un bac",
    "Montée de talon en boîte pour se rétablir",
    "Attraper la main seulement après être remonté sur le talon",
    "Remplacer une compression de main par un talon pour aller chercher plus haut",
    "Talon dans les deux mains pour se mettre de profil",
    "Opposition de pieds",
    "Opposition mains ou pieds pour faire bouger les autres membres",
    "Croisé puis décroisé de mains",
    "Croisé puis décroisé de pieds",
    "Croisé de pied en équilibre",
    "Croisé de pied sans les mains",
    "Jeté équilibre sur prise de pied sans mains",
    "No-hand avec pied haut et montée pour atteindre la main",
    "Se relever en équilibre",
    "Se lever avec main inverse pour grosse inversée très haute prise par dessous",
    "Une main, un pied aligné, autre main haute et loin pour forcer le drapeau",
    "Penché vers la droite avec main orientée vers soi, décalage progressif",
    "Mouvement étoile collé au mur avec montée de pied",
    "Épaule de profil avec main gauche basse et main droite haute",
    "Main basse bras tendu avec pieds dessous et main loin en diagonale",
    "Se relever sec avec prise utilisable dans un seul sens",
    "Équilibre avec une main indispensable pour ne pas tomber",
    "Opposition pied-main pour aller chercher une main derrière",
    "Opposition de mains physique sans pieds",
    "Opposition d'une main et du pied du même côté pour pousser",
    "Lolotte avec genou en bas pour rester collé au mur",
    "Paume bras tendu",
    "Transition épaule vers paume bras tendu avec changement de pied",
    "Coordination pour se lever sur la main utilisée",
    "Coordination pour se redresser sur un pied et compression de main",
    "Jeté dans une main bonne d'un seul côté avec relance",
    "Jeté en gardant une main de départ",
    "Jeté en croisé avec perte des pieds",
    "Compression debout mains hautes et pied",
    "Compression avec une main au-dessus pour garder l'équilibre",
    "Mouvement allongé avec contre-pointe gauche et relance de main",
    "Coordination équilibre à récupérer en décroisant les pieds",
    "Équilibre en se laissant tomber sur un pied ou une paume",
    "Départ assis et relevé sec pour récupérer l'équilibre",
    "Pied sur prise très penchée et relevé explosif",
    "Pied horizontal gainant au mur avec micro-prise",
    "Montée de pied à la même hauteur en allongé avec épaule",
    "Paume pour monter le pied dans la main (triceps)",
    "Paumes bras tendus écartés sans pieds",
    "Paume triceps devant le ventre pour se gainer",
    "Paume basse et autre main très haute sans pieds",
    "Relance avec deux prises superposées",
    "Bonne main basse et main horrible bras levé pour se jeter",
    "Pied haut impliquant no-foot",
    "Run and jump dans une main et un pied plus loin",
    "Run and jump pied gauche puis pied droit et une main",
    "Deux mains en compression avec pied haut et changement de pied",
    "Compression avec main horizontale et verticale collée",
    "Mains proches avec talon loin pour pouvoir lâcher une main",
    "Position étoile avec mains et pieds éloignés pour éviter la porte",
    "Équilibre no-hand avec montée de pied pour se relancer",
    "Rotation à 180° autour d'un pied",
    "Demi-tour sur un pied face au tapis",
    "Main plus à gauche que les pieds avec lancer de pied droit",
    "En boîte avec pieds hauts et mains basses",
    "Pied haut dans les mains bras tendus pour se mettre debout",
    "Relance de main depuis une compression vers une autre",
    "Ramener obligatoire pour aller chercher une prise lointaine",
    "Regroupement des mains avec relance croisée",
    "Pied l'un au-dessus de l'autre pour tendre un pied loin et haut",
    "Bras obligé de s'ouvrir pour atteindre une prise trop loin",
    "Perdre un pied pour atteindre la prochaine prise",
    "Pied haut permettant de lâcher une main",
    "Bras tendu sous la prise en inversée pour ramener",
    "Main droite et pied gauche avec gainage pour aller chercher main gauche",
    "Changement de pied avec ou sans main",
    "Changement de main",
    "Ramener une main sur l'autre",
    "Compression pied et main basse pour lever le bassin",
    "Compression à deux mains avec remplacement par talon",
    "Compression de pied en grenouille",
    "Compression talon et main",
    "Jambe pliée avec main à aller chercher plus loin",
    "Main droite basse, main gauche haute avec montée de pied en souplesse",
    "Position presque assise sur un pied avec main de plus en plus loin",
    "Muscle-up pour monter le pied dans la main",
    "En boîte avec main basse et pied droit haut",
    "Montée de pied haut de profil pour se rétablir",
    "Montée de pied de profil avec genou qui monte au torse",
    "Deux mains orientées dans le sens du grimpeur à rapprocher au torse",
    "Mains serrées avec pied haut pour fermer les bras",
    "Coincement de genou pour remonter la main du même côté",
    "Traction avec deux mains sur la même prise et pied mauvais",
    "Deux mains écartées avec déplacement extrême des pieds",
    "Alignement vertical pied-main provoquant une porte",
    "Avec une inversée, une main alignée au-dessus et montée de pied très haute sous l'inversée"
  ]
